foreach(REQUIRED_VARIABLE IN ITEMS SOURCE_DIR BINARY_DIR MOBAGEN_SOURCE_DIR CPM_FILE HOST_GENERATOR)
  if(NOT DEFINED ${REQUIRED_VARIABLE} OR "${${REQUIRED_VARIABLE}}" STREQUAL "")
    message(FATAL_ERROR "${REQUIRED_VARIABLE} is required")
  endif()
endforeach()

if(NOT EXISTS "${CPM_FILE}")
  message(FATAL_ERROR "The CPM module used by the host does not exist: ${CPM_FILE}")
endif()

file(REMOVE_RECURSE "${BINARY_DIR}")

set(CONFIGURE_COMMAND
    "${CMAKE_COMMAND}" -S "${SOURCE_DIR}" -B "${BINARY_DIR}" -G "${HOST_GENERATOR}"
    "-DMOBAGEN_SOURCE_DIR=${MOBAGEN_SOURCE_DIR}" "-DCPM_FILE=${CPM_FILE}"
)
if(DEFINED HOST_GENERATOR_PLATFORM AND NOT "${HOST_GENERATOR_PLATFORM}" STREQUAL "")
  list(APPEND CONFIGURE_COMMAND -A "${HOST_GENERATOR_PLATFORM}")
endif()
if(DEFINED HOST_GENERATOR_TOOLSET AND NOT "${HOST_GENERATOR_TOOLSET}" STREQUAL "")
  list(APPEND CONFIGURE_COMMAND -T "${HOST_GENERATOR_TOOLSET}")
endif()

execute_process(
  COMMAND ${CONFIGURE_COMMAND}
  RESULT_VARIABLE CONFIGURE_RESULT
  OUTPUT_VARIABLE CONFIGURE_OUTPUT
  ERROR_VARIABLE CONFIGURE_ERROR
)
if(NOT CONFIGURE_RESULT EQUAL 0)
  message(
    FATAL_ERROR "CPM legacy consumer configure failed:\n${CONFIGURE_OUTPUT}\n${CONFIGURE_ERROR}"
  )
endif()

execute_process(
  COMMAND "${CMAKE_COMMAND}" --build "${BINARY_DIR}" --config "${HOST_CONFIG}" --parallel 2 --target
          MobagenLegacyCoreConsumer
  RESULT_VARIABLE BUILD_RESULT
  OUTPUT_VARIABLE BUILD_OUTPUT
  ERROR_VARIABLE BUILD_ERROR
)
if(NOT BUILD_RESULT EQUAL 0)
  message(FATAL_ERROR "CPM legacy consumer build failed:\n${BUILD_OUTPUT}\n${BUILD_ERROR}")
endif()

execute_process(
  COMMAND "${CMAKE_CTEST_COMMAND}" --test-dir "${BINARY_DIR}" -C "${HOST_CONFIG}"
          --output-on-failure
  RESULT_VARIABLE TEST_RESULT
  OUTPUT_VARIABLE TEST_OUTPUT
  ERROR_VARIABLE TEST_ERROR
)
if(NOT TEST_RESULT EQUAL 0)
  message(FATAL_ERROR "CPM legacy consumer execution failed:\n${TEST_OUTPUT}\n${TEST_ERROR}")
endif()
