foreach(REQUIRED_VARIABLE IN ITEMS SOURCE_DIR BINARY_DIR INSTALL_PREFIX HOST_BINARY_DIR
                                   HOST_GENERATOR
)
  if(NOT DEFINED ${REQUIRED_VARIABLE} OR "${${REQUIRED_VARIABLE}}" STREQUAL "")
    message(FATAL_ERROR "${REQUIRED_VARIABLE} is required")
  endif()
endforeach()

file(REMOVE_RECURSE "${BINARY_DIR}" "${INSTALL_PREFIX}")

execute_process(
  COMMAND "${CMAKE_COMMAND}" --install "${HOST_BINARY_DIR}" --config "${HOST_CONFIG}" --prefix
          "${INSTALL_PREFIX}" --component MobagenPluginSdk
  RESULT_VARIABLE INSTALL_RESULT
  OUTPUT_VARIABLE INSTALL_OUTPUT
  ERROR_VARIABLE INSTALL_ERROR
)
if(NOT INSTALL_RESULT EQUAL 0)
  message(FATAL_ERROR "SDK install failed:\n${INSTALL_OUTPUT}\n${INSTALL_ERROR}")
endif()

execute_process(
  COMMAND "${CMAKE_COMMAND}" -S "${SOURCE_DIR}" -B "${BINARY_DIR}" -G "${HOST_GENERATOR}"
          "-DCMAKE_PREFIX_PATH=${INSTALL_PREFIX}"
  RESULT_VARIABLE CONFIGURE_RESULT
  OUTPUT_VARIABLE CONFIGURE_OUTPUT
  ERROR_VARIABLE CONFIGURE_ERROR
)
if(NOT CONFIGURE_RESULT EQUAL 0)
  message(FATAL_ERROR "SDK consumer configure failed:\n${CONFIGURE_OUTPUT}\n${CONFIGURE_ERROR}")
endif()

execute_process(
  COMMAND "${CMAKE_COMMAND}" --build "${BINARY_DIR}" --config "${HOST_CONFIG}"
  RESULT_VARIABLE BUILD_RESULT
  OUTPUT_VARIABLE BUILD_OUTPUT
  ERROR_VARIABLE BUILD_ERROR
)
if(NOT BUILD_RESULT EQUAL 0)
  message(FATAL_ERROR "SDK consumer build failed:\n${BUILD_OUTPUT}\n${BUILD_ERROR}")
endif()
