file(GLOB HEADLESS_INC CONFIGURE_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/*.h
     ${CMAKE_CURRENT_SOURCE_DIR}/*.hpp
)

file(GLOB HEADLESS_SRC CONFIGURE_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp
     ${CMAKE_CURRENT_SOURCE_DIR}/*.c
)

install(FILES ${HEADLESS_INC} DESTINATION include/headless)

add_executable(headless ${HEADLESS_SRC} ${HEADLESS_INC})

target_link_libraries(headless PUBLIC core)
