file(GLOB HIDEANDSEEKSQUARED_INC CONFIGURE_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/*.h
     ${CMAKE_CURRENT_SOURCE_DIR}/*.hpp
)

file(GLOB HIDEANDSEEKSQUARED_SRC CONFIGURE_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp
     ${CMAKE_CURRENT_SOURCE_DIR}/*.c
)

install(FILES ${HIDEANDSEEKSQUARED_INC} DESTINATION include/hideandseeksquared)

add_executable(hideandseeksquared ${HIDEANDSEEKSQUARED_SRC} ${HIDEANDSEEKSQUARED_INC})

target_link_libraries(hideandseeksquared PUBLIC core mobagen::core_random)
